### ISSUE TITLE
Skriv utförligare seed-data

### ISSUE THREAD

**Issue by jsvensson** [SU15-TeamAbsolut/Kundbolaget#63]
- 20-30 produkter, plocka data från Systembolaget
 - Unik adress för varje lokal/kund etc
 - 2-3 leveransadresser per kund
 - Vettiga leverantörsnamn

**Comment by Phoenix5793** [comment]
Jag börjar med Categories
nu finns 10 Categorier

**Comment by zundell88** [comment]
Jag kör adresser
-21 st adresser finns
--Väntar på ToString för Adress

**Comment by Phoenix5793** [comment]
tog även Supplliers
alla suppliers är nu faktiska  sprit tillverkare

**Comment by zundell88** [comment]
Lägger till produkter

**Comment by Phoenix5793** [comment]
alla adress tilldelningar har fått unika adresser tilldelade
